import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner/banner'
import NavBar from '@/components/nav/navbar'
import SectionCards from '@/components/card/sectioncards'
import { getPopularVideos, getVideos } from '@/lib/videos'



export async function getServerSideProps(){
  const disneyVideos= await getVideos("disney trailer");
  const productivityVideos= await getVideos("Productivity");
  const travelVideos= await getVideos("Travel");
  // const musicVideos= await getVideos("Beyonce");
  const popularVideos= await getPopularVideos();
  return{
    props:{
      disneyVideos,travelVideos,productivityVideos,popularVideos
    }
  }
};


export default function Home({disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {


  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <NavBar username='larisa@lari.com'/>
      <Banner
      videoId='4zH5iYM4wJo'
      title='Clifford the red dog'
      subTitle='a very cute dog'
      imgUrl='/static/dog.jpg'
      />
      <SectionCards title='Disney' videos={disneyVideos}/>
      <SectionCards title='Travel' videos={travelVideos}/>
      <SectionCards title='Productivity' videos={productivityVideos}/>
      {/* <SectionCards title='Chill Pop Music' videos={musicVideos}/> */}
      <SectionCards title='Popular' videos={popularVideos}/>
       </div>
    
    </>
  )
}
