import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner/banner'
import NavBar from '@/components/nav/navbar'
import SectionCards from '@/components/card/sectioncards'
import { getPopularVideos, getVideos, getWatchItAgainVideos } from '@/lib/videos'
import useRedirectUser from './utils/redirectUser'

export async function getServerSideProps(context){

 const{userId, token}= await useRedirectUser(context);
 if(!userId){
  return{
    props:{},
    redirect:{
      destination:'/login',
      permanent:false,
    }
  }
}
  const watchItAgainVideos=await getWatchItAgainVideos(userId, token);
  const disneyVideos= await getVideos("disney movies");
  const productivityVideos= await getVideos("Productivity");
  const travelVideos= await getVideos("Travel");
  const popularVideos= await getPopularVideos();

  return{
    props:{
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      watchItAgainVideos
    }
  }
};

export default function Home({disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
  watchItAgainVideos=[]
}) {

return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/icon.png" />
      </Head>
      <div className={styles.container}>
      <NavBar/>
      <Banner
      videoId='CaimKeDcudo'
      title='Encanto'
      subTitle='“Encanto” tells the tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto.'
      imgUrl='/static/header.jpg'
      />
      <SectionCards title='Disney' videos={disneyVideos} size='large'/>
      <SectionCards title='Watch it again' videos={watchItAgainVideos} size='medium'/> 
      <SectionCards title='Travel' videos={travelVideos} size='small'/>
      <SectionCards title='Productivity' videos={productivityVideos} size='small'/> 
       <SectionCards title='Popular' videos={popularVideos} size='large'/>
       </div>
    
    </>
  )
}
